name:  macOS Monterey latest

on:
  push:
    branches: [ master, struct_pb ]
  pull_request:
    branches: [ master, struct_pb ]
    
jobs:
  build:
    strategy:
      matrix:
        mode: [ Debug, Release ]
        cpp_version: [17, 20]
        
    runs-on: macos-latest
    
    steps:
    - name: check out
      uses: actions/checkout@v3
      
    - name: configure cmake
      run:  CXX=clang++ CC=clang cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}
      
    - name: test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.mode }} -j 1 -V
